### ISSUE TITLE
failing to run in codeceptjs/codeceptjs docker image

### ISSUE THREAD

**Issue by aschmidtwork** [codeceptjs/codeceptjs-resemblehelper#105]
i would like to use this in codeceptjs/codeceptjs docker container, but i'm not sure if i'm doing it right.

this dockerfile builds fine:
```dockerfile
FROM codeceptjs/codeceptjs
RUN npm install codeceptjs-resemblehelper --prefix /codecept
```

but running the docker container gives these errors:
```
Could not load helper ResembleHelper from module 'codeceptjs-resemblehelper':
Cannot find module 'codeceptjs/lib/container'
Require stack:
- /codecept/node_modules/codeceptjs-resemblehelper/index.js
- /codecept/lib/container.js
- /codecept/lib/codecept.js
- /codecept/bin/codecept.js
Error: Cannot find module 'codeceptjs/lib/container'
Require stack:
- /codecept/node_modules/codeceptjs-resemblehelper/index.js
- /codecept/lib/container.js
- /codecept/lib/codecept.js
- /codecept/bin/codecept.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/codecept/node_modules/codeceptjs-resemblehelper/index.js:9:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)

Error:
    at createHelpers (/codecept/lib/container.js:182:13)
    at Function.create (/codecept/lib/container.js:43:25)
    at Codecept.init (/codecept/lib/codecept.js:56:15)
    at Command.module.exports (/codecept/lib/command/run.js:24:14)
    at Command.listener (/codecept/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:375:28)
    at Command.parseArgs (/codecept/node_modules/commander/index.js:651:12)
    at Command.parse (/codecept/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/codecept/bin/codecept.js:192:9)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
C:\docker\as\as-jtlshop5-dev\plugins\UpwaveEnergielabel\tests
```

**Comment by neo-escieur** [comment]
is this project alive ?

resemblehelper not working with docker codeceptjs

**Comment by PeterNgTr** [comment]
I think this should work

FROM codeceptjs/codeceptjs
RUN npm install codeceptjs-resemblehelper

**Comment by sharath2106** [comment]
@aschmidtwork Does the step mentioned by @kobenguyent helped you? If it did, i would close this issue.

**Comment by neo-escieur** [comment]
this is the first try i made and it was not ok.
I will test the new version this week
