### ISSUE TITLE
Installation fails with node16+

### ISSUE THREAD

**Issue by ngraf** [codeceptjs/codeceptjs-resemblehelper#87]
I can't install the package `codeceptjs-resemblehelper` anymore because of `gyp`

`npm install codeceptjs-resemblehelper`
fails with HTTP 404 in:
`error response status 404 Not Found on https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-linux-glibc-x64.tar.gz`

Executed in docker image: `mcr.microsoft.com/playwright:focal`
It worked some weeks ago in exactly the same setup. I am afraid the dependency `gyp` is now completely broken.

Detailed output:
```
npm WARN deprecated querystring@0.2.0: The
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code 1
npm ERR! path /test/node_modules/resemblejs/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/test/node_modules/resemblejs/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/test/node_modules/resemblejs/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.5
npm ERR! node-pre-gyp info using node@16.4.0 | linux | x64
npm ERR! node-pre-gyp info check checked for "/test/node_modules/resemblejs/node_modules/canvas/build/Release/canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-linux-glibc-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-linux-glibc-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.6.1 and node@16.4.0 (node-v93 ABI, glibc) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-linux-glibc-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.4.0 | linux | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.4.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v16.4.0/node-v16.4.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.4.0/node-v16.4.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v16.4.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.4.0/SHASUMS256.txt
npm ERR! (node:69) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/test/node_modules/resemblejs/node_modules/canvas/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/16.4.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.4.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.4.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/test/node_modules/resemblejs/node_modules/canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: 1: pkg-config: not found
npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.10.25-linuxkit
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/test/node_modules/resemblejs/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/test/node_modules/resemblejs/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd /test/node_modules/resemblejs/node_modules/canvas
npm ERR! gyp ERR! node -v v16.4.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/test/node_modules/resemblejs/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/test/node_modules/resemblejs/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/test/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Linux 5.10.25-linuxkit
npm ERR! node-pre-gyp ERR! command "/usr/bin/node" "/test/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /test/node_modules/resemblejs/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v16.4.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.5
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-13T10_49_05_699Z-debug.log
```

**Comment by puneet0191** [comment]
thanks a lot for looking into this, Will look into this.

**Comment by puneet0191** [comment]
@ngraf are you still facing this issue, I have been able to make it work on my system

```
node v12.22.1
```

**Comment by ngraf** [comment]
I found out it is related to **node16**

You can reproduce:
`docker run --rm node:15 sh -c "mkdir test; cd test; npm install codeceptjs-resemblehelper"` 💚
`docker run --rm node:16 sh -c "mkdir test; cd test; npm install codeceptjs-resemblehelper"` 🔴<

Downgrade version of `node` is not an option for me, because of reasons. Therefor it would be helpful to find a solution, or at least mark the package as not compatible with node16+

**Comment by kiran37** [comment]
This PR should fix the issue: https://github.com/codeceptjs/codeceptjs-resemblehelper/pull/101

**Comment by umeshperera** [comment]
Still facing the same issue in node v17.5.0

**Comment by gunta** [comment]
Still not fixed, macOS here

**Comment by JonnyCodes** [comment]
Saw this issue as well, updating resembleJS to 4.1.0 fixed it for me. 
I did it by adding an override into my own package.json.

**Comment by jamesfarmer171** [comment]
plus one to the above comment about needed to updated resembleJS to 4.1.0

**Comment by StasGrishaevTutu** [comment]
same issue here, NodeJS 18

**Comment by CACBelchior** [comment]
On my M1 computer, the problem that I was facing related to the 'canvas' installation was because that Apple M1 is based on arm, then can't find canvas-v2.7.0-node-v72-darwin-unknown-arm64.tar.gz, cause there is only canvas-v2.7.0-node-v72-darwin-unknown-x64.tar.gz.

This worked for me:

`arch -arm64 brew install pkg-config cairo pango libpng jpeg giflib librsvg`

and then:

`npm install codeceptjs-resemblehelper`

**Comment by sharath2106** [comment]
We have released the latest version ([1.9.7](https://www.npmjs.com/package/codeceptjs-resemblehelper)) of the library yesterday. I would ask to check against the latest version and let us know.

**Comment by ngraf** [comment]
@sharath2106 , thanks for fixing.

I can *confirm* it is fixed in >1.9.6. 💚

npm install codeceptjs-resemblehelper@1.9.5-> 🔴 

npm install codeceptjs-resemblehelper@1.9.6 -> ✅

**Comment by puneet0191** [comment]
@ngraf  it is your love and dedication that we live for :heart:

**Comment by openmindculture** [comment]
Thanks for the fix / instructions. To make it work on Ubuntu Linux, I had to install the required OS components [as suggested by Automattic](https://github.com/Automattic/node-canvas/wiki/Installation%3A-Ubuntu-and-other-Debian-based-systems):

`sudo apt install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev`

then I could `npm install codeceptjs-resemblehelper@1.9.6`
